import {
  amazonShopURLValidation,
  appleMusicURLValidation,
  emailAddressValidation,
  facebookURLValidation,
  gitHubURLValidation,
  instagramThreadsUsernameValidation,
  linkedInURLValidation,
  personalWebsiteURLValidation,
  phoneNumberValidation,
  snapchatURLValidation,
  soundCloudURLValidation,
  spotifyURLValidation,
  telegramURLValidation,
  twitterXUsernameValidation,
  whatsappChannelURLValidation,
  youtubeURLValidation,
} from "@/validations";
import {
  InstagramLogo,
  AmazonLogo,
  ChatCircle,
  Envelope,
  FacebookLogo,
  GithubLogo,
  Globe,
  LinkedinLogo,
  MusicNotes,
  Phone,
  SnapchatLogo,
  SoundcloudLogo,
  SpotifyLogo,
  TelegramLogo,
  ThreadsLogo,
  WhatsappLogo,
  XLogo,
  YoutubeLogo,
} from "@phosphor-icons/react";

export const socialChannelList = [
  {
    name: "Instagram",
    slug: "instagram",
    icon: <InstagramLogo size={24} />,
    placeholder: "Enter Instagram Username*",
    example: "@instagramusername",
    validation: instagramThreadsUsernameValidation,
  },
  {
    name: "Threads",
    slug: "threads",
    icon: <ThreadsLogo size={24} />,
    placeholder: "Enter Threads Username*",
    example: "@threadsusername",
    validation: instagramThreadsUsernameValidation,
  },
  {
    name: "Email",
    slug: "email",
    icon: <Envelope size={24} />,
    placeholder: "Enter Email Address*",
    example: "your@emailaddress.com",
    validation: emailAddressValidation,
  },
  {
    name: "Facebook",
    slug: "facebook",
    icon: <FacebookLogo size={24} />,
    placeholder: "Enter Facebook URL*",
    example: "https://facebook.com/facebookpageurl",
    validation: facebookURLValidation,
  },
  {
    name: "YouTube",
    slug: "youtube",
    icon: <YoutubeLogo size={24} />,
    placeholder: "Enter YouTube URL*",
    example: "https://youtube.com/channel/youtubechannelurl",
    validation: youtubeURLValidation,
  },
  {
    name: "X (Formerly Twitter)",
    slug: "x-twitter",
    icon: <XLogo size={24} />,
    placeholder: "Enter X (formerly Twitter) Handle*",
    example: "@yourxhandle",
    validation: twitterXUsernameValidation,
  },
  {
    name: "WhatsApp",
    slug: "whatsapp",
    icon: <WhatsappLogo size={24} />,
    placeholder: "Enter WhatsApp Number*",
    example: "+919876543210",
    validation: phoneNumberValidation,
  },
  {
    name: "WhatsApp Channel",
    slug: "whatsapp-channel",
    icon: <ChatCircle size={24} />,
    placeholder: "Enter WhatsApp Channel URL*",
    example: "https://www.whatsapp.com/channel/yourchannel",
    validation: whatsappChannelURLValidation,
  },
  {
    name: "Snapchat",
    slug: "snapchat",
    icon: <SnapchatLogo size={24} />,
    placeholder: "Enter Snapchat URL*",
    example: "https://www.snapchat.com/add/yourusername",
    validation: snapchatURLValidation,
  },
  {
    name: "Amazon",
    slug: "amazon",
    icon: <AmazonLogo size={24} />,
    placeholder: "Enter Amazon URL*",
    example: "https://amazon.com/shop/yourshopname",
    validation: amazonShopURLValidation,
  },
  {
    name: "Linkedin",
    slug: "linkedin",
    icon: <LinkedinLogo size={24} />,
    placeholder: "Enter Linkedin URL*",
    example: "https://linkedin.com/in/username",
    validation: linkedInURLValidation,
  },
  {
    name: "Github",
    slug: "github",
    icon: <GithubLogo size={24} />,
    placeholder: "Enter Github URL*",
    example: "https://www.github.com/username",
    validation: gitHubURLValidation,
  },
  {
    name: "Phone",
    slug: "phone",
    icon: <Phone size={24} />,
    placeholder: "Enter Phone Number*",
    example: "+919876543210",
    validation: phoneNumberValidation,
  },
  {
    name: "Telegram",
    slug: "telegram",
    icon: <TelegramLogo size={24} />,
    placeholder: "Enter Telegram URL*",
    example: "https://t.me/",
    validation: telegramURLValidation,
  },
  {
    name: "Soundcloud",
    slug: "soundcloud",
    icon: <SoundcloudLogo size={24} />,
    placeholder: "Enter Soundcloud URL*",
    example: "https://soundcloud.com/username",
    validation: soundCloudURLValidation,
  },
  {
    name: "Spotify",
    slug: "spotify",
    icon: <SpotifyLogo size={24} />,
    placeholder: "Enter Spotify URL*",
    example: "https://open.spotify.com/artist/artistname",
    validation: spotifyURLValidation,
  },
  {
    name: "Apple Music",
    slug: "apple-music",
    icon: <MusicNotes size={24} />,
    placeholder: "Enter Apple Music URL*",
    example: "https://music.apple.com/us/album/youralbum",
    validation: appleMusicURLValidation,
  },
  {
    name: "Personal Website",
    slug: "personal-website",
    icon: <Globe size={24} />,
    placeholder: "Enter Personal Website URL*",
    example: "https://www.yourwebsite.com",
    validation: personalWebsiteURLValidation,
  },
];
